language: node_js
node_js:
  - 6
install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  - ./deploy-staging.sh
  - node node_modules/lighthouse-ci/runlighthouse.js https://hnpwa-firebase-staging.firebaseapp.com
